2022-03-09 20:13:17.574 [error] <0.363.0>@submission_queue:hello:{61,12} Hello
2022-03-11 10:04:25.357 [error] <0.379.0>@utility:query:{25,27} Database query error: {error,error,<<"42703">>,undefined_column,<<"column \"technology\" does not exist">>,[{file,<<"parse_relation.c">>},{line,<<"3514">>},{position,<<"40">>},{routine,<<"errorMissingColumn">>},{severity,<<"ERROR">>}]}
2022-03-11 10:04:25.360 [error] <0.372.0>@cache_service:load_cache:57 Supervisor github_webhook_service_sup had child cache_service started with cache_service:start_link() at undefined exit with reason no match of right hand value error in cache_service:load_cache/0 line 57 in context start_error
2022-03-11 10:04:25.360 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,cache_service,{{badmatch,error},[{cache_service,load_cache,0,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,57}]},{cache_service,init,1,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,30}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 142
2022-03-11 10:07:03.588 [error] <0.379.0>@utility:query:{25,27} Database query error: {error,error,<<"42703">>,undefined_column,<<"column \"technology\" does not exist">>,[{file,<<"parse_relation.c">>},{line,<<"3514">>},{position,<<"40">>},{routine,<<"errorMissingColumn">>},{severity,<<"ERROR">>}]}
2022-03-11 10:07:03.589 [error] <0.372.0>@cache_service:load_cache:57 Supervisor github_webhook_service_sup had child cache_service started with cache_service:start_link() at undefined exit with reason no match of right hand value error in cache_service:load_cache/0 line 57 in context start_error
2022-03-11 10:08:51.375 [error] <0.369.0>@utility:query:{25,27} Database query error: {error,error,<<"42501">>,insufficient_privilege,<<"permission denied for table team">>,[{file,<<"aclchk.c">>},{line,<<"3466">>},{routine,<<"aclcheck_error">>},{severity,<<"ERROR">>}]}
2022-03-11 10:08:51.376 [error] <0.362.0>@cache_service:load_cache:57 Supervisor github_webhook_service_sup had child cache_service started with cache_service:start_link() at undefined exit with reason no match of right hand value error in cache_service:load_cache/0 line 57 in context start_error
2022-03-11 10:08:51.376 [error] <0.369.0>@cache_service:load_cache:57 CRASH REPORT Process <0.369.0> with 1 neighbours crashed with reason: no match of right hand value error in cache_service:load_cache/0 line 57
2022-03-11 10:08:51.376 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,cache_service,{{badmatch,error},[{cache_service,load_cache,0,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,57}]},{cache_service,init,1,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,30}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 142
2022-03-11 10:12:54.816 [error] <0.369.0>@utility:query:{25,27} Database query error: {error,error,<<"42501">>,insufficient_privilege,<<"permission denied for table team">>,[{file,<<"aclchk.c">>},{line,<<"3466">>},{routine,<<"aclcheck_error">>},{severity,<<"ERROR">>}]}
2022-03-11 10:12:54.817 [error] <0.362.0>@cache_service:load_cache:57 Supervisor github_webhook_service_sup had child cache_service started with cache_service:start_link() at undefined exit with reason no match of right hand value error in cache_service:load_cache/0 line 57 in context start_error
2022-03-11 10:12:54.817 [error] <0.369.0>@cache_service:load_cache:57 CRASH REPORT Process <0.369.0> with 1 neighbours crashed with reason: no match of right hand value error in cache_service:load_cache/0 line 57
2022-03-11 10:12:54.817 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,cache_service,{{badmatch,error},[{cache_service,load_cache,0,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,57}]},{cache_service,init,1,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,30}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 142
2022-03-11 10:47:00.466 [error] <0.379.0>@utility:query:{25,27} Database query error: {error,error,<<"42501">>,insufficient_privilege,<<"permission denied for table team">>,[{file,<<"aclchk.c">>},{line,<<"3466">>},{routine,<<"aclcheck_error">>},{severity,<<"ERROR">>}]}
2022-03-11 10:47:00.467 [error] <0.372.0>@cache_service:load_cache:57 Supervisor github_webhook_service_sup had child cache_service started with cache_service:start_link() at undefined exit with reason no match of right hand value error in cache_service:load_cache/0 line 57 in context start_error
2022-03-11 10:47:00.468 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,cache_service,{{badmatch,error},[{cache_service,load_cache,0,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,57}]},{cache_service,init,1,[{file,"/home/amirhosein/Documents/aut-backend-contest-1400/github_webhook_service/src/cache_service.erl"},{line,30}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 142
2022-03-12 11:35:35.475 [error] <0.376.0>@utility:query:{25,27} Database query error: {error,error,<<"42702">>,ambiguous_column,<<"column reference \"repository_full_name\" is ambiguous">>,[{file,<<"parse_relation.c">>},{line,<<"891">>},{position,<<"23">>},{routine,<<"colNameToVar">>},{severity,<<"ERROR">>}]} when query was "SELECT delivery_guid, repository_full_name, repository_name, repository_clone_url,\n            repository_owner_login, head_commit_id, head_commit_message, head_commit_timestamp,\n            pushed_at_timestamp, technology\n            FROM submission as s, team as t WHERE s.repository_full_name = t.repository_full_name AND status = $1"
2022-03-12 11:35:35.480 [error] <0.376.0>@database_service:handle_call:42 gen_server database_service terminated with reason: no match of right hand value error in database_service:handle_call/3 line 42
2022-03-12 11:35:35.480 [error] <0.376.0>@database_service:handle_call:42 CRASH REPORT Process database_service with 1 neighbours crashed with reason: no match of right hand value error in database_service:handle_call/3 line 42
2022-03-12 11:35:35.480 [error] <0.374.0>@database_service:handle_call:42 Supervisor github_webhook_service_sup had child database_service started with database_service:start_link() at <0.376.0> exit with reason no match of right hand value error in database_service:handle_call/3 line 42 in context child_terminated
2022-03-12 11:36:01.491 [error] <0.387.0>@utility:query:{25,27} Database query error: {error,error,<<"42702">>,ambiguous_column,<<"column reference \"repository_full_name\" is ambiguous">>,[{file,<<"parse_relation.c">>},{line,<<"891">>},{position,<<"23">>},{routine,<<"colNameToVar">>},{severity,<<"ERROR">>}]} when query was "SELECT delivery_guid, repository_full_name, repository_name, repository_clone_url,\n            repository_owner_login, head_commit_id, head_commit_message, head_commit_timestamp,\n            pushed_at_timestamp, technology\n            FROM submission as s, team as t WHERE s.repository_full_name = t.repository_full_name AND status = $1"
2022-03-12 11:36:01.491 [error] <0.387.0>@database_service:handle_call:42 gen_server database_service terminated with reason: no match of right hand value error in database_service:handle_call/3 line 42
2022-03-12 11:36:01.491 [error] <0.387.0>@database_service:handle_call:42 CRASH REPORT Process database_service with 1 neighbours crashed with reason: no match of right hand value error in database_service:handle_call/3 line 42
2022-03-12 11:36:01.491 [error] <0.374.0>@database_service:handle_call:42 Supervisor github_webhook_service_sup had child database_service started with database_service:start_link() at <0.387.0> exit with reason no match of right hand value error in database_service:handle_call/3 line 42 in context child_terminated
2022-03-12 11:38:21.734 [error] emulator Error in process <0.387.0> with exit value:
{{badmatch,0},[{submission_queue,judge,1,[{file,"/home/amirhosein/aut-backend-contest-1400/src/submission_queue.erl"},{line,144}]}]}
2022-03-12 11:55:05.538 [error] emulator Error in process <0.386.0> with exit value:
{{badmatch,0},[{submission_queue,judge,1,[{file,"/home/amirhosein/aut-backend-contest-1400/src/submission_queue.erl"},{line,147}]}]}
2022-03-12 12:02:42.232 [error] emulator Error in process <0.386.0> with exit value:
{{badmatch,0},[{submission_queue,judge,1,[{file,"/home/amirhosein/aut-backend-contest-1400/src/submission_queue.erl"},{line,148}]}]}
2022-03-12 12:08:01.337 [error] <0.378.0>@epgsql_codec_boolean:encode:26 gen_server <0.378.0> terminated with reason: no function clause matching epgsql_codec_boolean:encode(<<"judged">>, bool, []) line 26
2022-03-12 12:08:01.337 [error] <0.378.0>@epgsql_codec_boolean:encode:26 CRASH REPORT Process <0.378.0> with 1 neighbours crashed with reason: no function clause matching epgsql_codec_boolean:encode(<<"judged">>, bool, []) line 26
2022-03-12 12:08:01.337 [error] <0.374.0>@epgsql_codec_boolean:encode:26 Supervisor github_webhook_service_sup had child database_service started with database_service:start_link() at <0.376.0> exit with reason no function clause matching epgsql_codec_boolean:encode(<<"judged">>, bool, []) line 26 in context child_terminated
2022-03-12 12:09:02.978 [error] <0.390.0>@submission_queue:handle_cast:83 gen_server submission_queue terminated with reason: no match of right hand value [] in submission_queue:handle_cast/2 line 83
2022-03-12 12:09:02.978 [error] <0.390.0>@submission_queue:handle_cast:83 CRASH REPORT Process submission_queue with 0 neighbours crashed with reason: no match of right hand value [] in submission_queue:handle_cast/2 line 83
2022-03-12 12:09:02.978 [error] <0.374.0>@submission_queue:handle_cast:83 Supervisor github_webhook_service_sup had child submission_queue started with submission_queue:start_link() at <0.390.0> exit with reason no match of right hand value [] in submission_queue:handle_cast/2 line 83 in context child_terminated
2022-03-12 14:04:44.952 [error] <0.363.0>@submission_queue:handle_cast:83 gen_server submission_queue terminated with reason: no match of right hand value [] in submission_queue:handle_cast/2 line 83
2022-03-12 14:04:44.952 [error] <0.363.0>@submission_queue:handle_cast:83 CRASH REPORT Process submission_queue with 0 neighbours crashed with reason: no match of right hand value [] in submission_queue:handle_cast/2 line 83
2022-03-12 14:04:44.952 [error] <0.362.0>@submission_queue:handle_cast:83 Supervisor github_webhook_service_sup had child submission_queue started with submission_queue:start_link() at <0.363.0> exit with reason no match of right hand value [] in submission_queue:handle_cast/2 line 83 in context child_terminated
